@startuml class-diagram

hide empty members
!theme blueprint
!pragma useIntermediatePackages false

package "io.github.masmangan.assis" {
class AssisApp <<final>> {
  + main(args : String[]) : void {static}
}
class GenerateClassDiagram {
  - {static} DOCS_UML_CLASS_DIAGRAM_PUML : String {final}
  - {static} SRC_MAIN_JAVA : String {final}
  - {static} logger : Logger {final}
  + generate() : void {static}
  + generate(src : Path, out : Path) : void {static}
}
enum Kind {
}
enum Modifier {
}
}

left to right direction

center footer
Generated with ASSIS (Java -> UML) at 2025-12-23T17:17:32Z
https://github.com/masmangan/assis
end footer

@enduml
